05_pjt/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete')
]

05_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('books/', include('books.urls')),
]

05_pjt/books/models.py
from django.db import models

# Create your models here.


class Book(models.Model):

    # 회원 리뷰 평점
    RATING_CHOICES = [
        (1, "1"),
        (2, "2"),
        (3, "3"),
        (4, "4"),
        (5, "5"),
    ]

    rating = models.PositiveIntegerField(
        choices=RATING_CHOICES,
        default=5,
        help_text="PLEASE ENTER RATING",
        verbose_name="RATING",
    )

    title = models.CharField(max_length=100, verbose_name="TITLE")
    description = models.TextField(blank=True, verbose_name="DESCRIPTION")
    author = models.CharField(max_length=50, verbose_name="AUTHOR")
    
    

05_pjt/books/forms.py
from django import forms

from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'description', 'rating', 'author']
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'ENTER TITLE',
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'ENTER DETAILED DESCRIPTION',
                    'rows': 4,
                    'style': 'height: 120px !important; resize: none;',
                }
            ),
            'rating': forms.Select(
                attrs={
                    'class': 'form-select',
                }
            ),
            'author': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
        }
        labels = {
            'title': 'TITLE',
            'description': 'DESCRIPTION',
            'rating': 'RATING',
            'author': 'AUTHOR',
        }
        
        
class UpdateBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'description', 'rating', 'author']
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'ENTER TITLE',
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'ENTER DETAILED DESCRIPTION',
                    'rows': 4,
                    'style': 'height: 120px !important; resize: none;',
                }
            ),
            'rating': forms.Select(
                attrs={
                    'class': 'form-select',
                }
            ),
            'author': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
        }
        labels = {
            'title': 'TITLE',
            'description': 'DESCRIPTION',
            'rating': 'RATING',
            'author': 'AUTHOR',
        }

05_pjt/books/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .forms import BookForm, UpdateBookForm
from .models import Book


# F12
@login_required
def index(request):
    books = Book.objects.all()
    context = {
        "books": books,
    }
    return render(request, "books/index.html", context)


# F13
@login_required
def create(request):
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            book = form.save()
            return redirect("books:index")
    else:
        form = BookForm()
    context = {
        "form": form,
    }
    return render(request, "books/create.html", context)


# F14
@login_required
def detail(request, pk):
    if request.method == "GET":
        book = Book.objects.get(pk=pk)

        context = {
            "book": book,
        }

        return render(request, "books/detail.html", context)


# F15
@login_required
def update(request, pk):
    book = Book.objects.get(pk=pk)
    if request.method == "POST":
        form = UpdateBookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect("books:detail", pk=pk)
    else:
        form = UpdateBookForm(instance=book)
    context = {
        "form": form,
        "book": book,
    }
    return render(request, "books/update.html", context)


# F16
@login_required
def delete(request, pk):
    book = Book.objects.get(pk=pk)
    if request.method == "POST":
        book.delete()
    return redirect("books:index")

05_pjt/books/templates/books/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="row mb-4">
    <div class="col-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'books:index' %}">HOME</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">ADD BOOK</li>
        </ol>
      </nav>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 mx-auto">
      <div class="card">
        <div class="card-header">
          <h5 class="mb-0">ADD BOOK</h5>
        </div>
        <div class="card-body">
          <form action="{% url 'books:create' %}" method="POST">
            {% csrf_token %}

            <div class="mb-3">
              <label for="{{ form.title.id_for_label }}" class="form-label">{{ form.title.label }}</label>
              {{ form.title }}
              {% if form.title.errors %}
                <div class="text-danger">
                  {% for error in form.title.errors %}
                    <small>{{ error }}</small>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="mb-3">
              <label for="{{ form.description.id_for_label }}" class="form-label">{{ form.description.label }}</label>
              {{ form.description }}
              {% if form.description.errors %}
                <div class="text-danger">
                  {% for error in form.description.errors %}
                    <small>{{ error }}</small>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="col-md-6 mb-3">
              <label for="{{ form.rating.id_for_label }}" class="form-label">{{ form.rating.label }}</label>
              {{ form.rating }}
              {% if form.rating.errors %}
                <div class="text-danger">
                  {% for error in form.rating.errors %}
                    <small>{{ error }}</small>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="col-md-6">
              <label for="{{ form.author.id_for_label }}" class="form-label">{{ form.author.label }}</label>
              {{ form.author }}
              {% if form.author.errors %}
                <div class="text-danger">
                  {% for error in form.author.errors %}
                    <small>{{ error }}</small>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="mb-3 form-check">
              {{ form.completed }}
              <label class="form-check-label" for="{{ form.completed.id_for_label }}">{{ form.completed.label }}</label>
              {% if form.completed.errors %}
                <div class="text-danger">
                  {% for error in form.completed.errors %}
                    <small>{{ error }}</small>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <a href="{% url 'books:index' %}" class="btn btn-secondary">CANCEL</a>
              <button type="submit" class="btn btn-primary">ADD</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

05_pjt/books/templates/books/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="row mb-4">
    <div class="col-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'books:index' %}">HOME</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">BOOK DETAIL</li>
        </ol>
      </nav>
    </div>
  </div>

  <div class="row">
    <div class="mb-4">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h5 class="mb-0">{{ book.title }}</h5>
        </div>
        <div class="card-body">
          <p class="card-text">{{ book.description }}</p>
          <hr />
          <p class="card-text">
            <strong>RATING: {{ book.review }} / 5</strong>
          </p>
          <p class="card-text">
            <strong>{{ book.author }}</strong>
          </p>

        <hr />
        <div class="col-md-4">
          <div class="d-flex gap-2">
            <a href="{% url 'books:update' book.pk %}" class="btn btn-secondary">UPDATE</a>
            <form action="{% url 'books:delete' book.pk %}" method="POST" onsubmit="return confirm('Are you sure you want to delete this book description? This action cannot be undone.');">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">DELETE</button>
            </form>
          </div>
        </div>
        <hr />

        <a href="{% url 'books:index' %}" class="btn btn-primary">BACK</a>
      </div>
    </div>
  </div>
  
  {% endblock %}

05_pjt/books/templates/books/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="row mb-4">
    <div class="col-md-8">
      <h1 class="mb-4">BOOK LIST</h1>
    </div>
    <div class="col-md-4 text-end">
      <a href="{% url 'books:create' %}" class="btn btn-primary"><i class="bi bi-plus-circle"></i>+ ADD NEW BOOK</a>
    </div>
  </div>

{% if books %}
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for book in books %}
      <div class="col">
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title fw-bold">{{ book.title }}</h5>
            <p class="card-text description-limit">{{ book.description }}</p>
            <a href="{% url 'books:detail' book.pk %}" class="btn btn-primary">DETAIL</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% else %}
  <div class="row">
    <div class="col-12">
      <div class="alert alert-info w-100 text-center" role="alert">
        <h4 class="alert-heading">NO BOOK AVAILABLE</h4>
        <p>PLEASE ADD NEW BOOK</p>
      </div>
    </div>
  </div>
{% endif %}


{% endblock %}

05_pjt/books/templates/books/update.html
{% extends 'base.html' %}

{% block content %}
  <div class="row mb-4">
    <div class="col-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'books:index' %}">HOME</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'books:detail' book.pk %}">BOOK DETAIL</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">EDIT BOOK</li>
        </ol>
      </nav>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 mx-auto">
      <div class="card">
        <div class="card-header">
          <h5 class="mb-0">EDIT BOOK</h5>
        </div>
        <div class="card-body">
          <form action="{% url 'books:update' book.pk %}" method="POST">
            {% csrf_token %}

            <div class="mb-3">
              <label for="{{ form.title.id_for_label }}" class="form-label">{{ form.title.label }}</label>
              {{ form.title }}
              {% if form.title.errors %}
                <div class="text-danger">
                  {% for error in form.title.errors %}
                    <small>{{ error }}</small>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="mb-3">
              <label for="{{ form.description.id_for_label }}" class="form-label">{{ form.description.label }}</label>
              {{ form.description }}
              {% if form.description.errors %}
                <div class="text-danger">
                  {% for error in form.description.errors %}
                    <small>{{ error }}</small>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="col-md-6 mb-3">
              <label for="{{ form.rating.id_for_label }}" class="form-label">{{ form.rating.label }}</label>
              {{ form.rating }}
              {% if form.rating.errors %}
                <div class="text-danger">
                  {% for error in form.rating.errors %}
                    <small>{{ error }}</small>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="col-md-6">
              <label for="{{ form.author.id_for_label }}" class="form-label">{{ form.author.label }}</label>
              {{ form.author }}
              {% if form.author.errors %}
                <div class="text-danger">
                  {% for error in form.author.errors %}
                    <small>{{ error }}</small>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <a href="{% url 'books:detail' book.pk %}" class="btn btn-secondary">CANCEL</a>
              <button type="submit" class="btn btn-warning">UPDATE BOOK</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}