05_pjt/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

05_pjt/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete')
]

05_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('books/', include('books.urls')),
]

05_pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous" /> <title>Book App</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />

    <style>
      body {
        font-family: 'Noto Sans', sans-serif;
        font-optical-sizing: auto;
        
      }
      .description-limit {
        display: -webkit-box;
        -webkit-line-clamp: 3; /* 보여줄 줄 수 */
        -webkit-box-orient: vertical;
        overflow: hidden;
        text-overflow: ellipsis;
        height: auto;
      }
    </style>
  </head>

  <body>
    <nav class="navbar bg-dark navbar-expand-lg border-bottom border-body mb-4" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'books:index' %}">ThRead</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto text-end mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'books:index' %}">HOME</a>
            </li>

            {% if request.user.is_authenticated %}
              {% comment %}create, myprofile 추가{% endcomment %}
              <li class="nav-item">
                <form action="{% url 'books:create' %}" method="POST">
                  {% csrf_token %}
                  <input class="nav-link" type="submit" value="CREATE" />
                </form>
              </li>
              <li class="nav-item">
                <form action="{% url 'accounts:profile' user.username %}" method="GET">
                  <input class="nav-link" type="submit" value="MY PROFILE" />
                </form>
              </li>

              <li class="nav-item">
                <form action="{% url 'accounts:delete' %}" method="POST" class="mt-0" onsubmit="return confirm('Are you sure you want to delete your account? This action cannot be undone.');">
                  {% csrf_token %}
                  <input class="nav-link" type="submit" value="DELETE ACCOUNT" />
                </form>
              </li>

              <li class="nav-item">
                <form action="{% url 'accounts:logout' %}" method="POST">
                  {% csrf_token %}
                  <input class="nav-link" type="submit" value="LOGOUT" />
                </form>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">LOGIN</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">SIGNUP</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      {% block content %}

      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
  </body>
</html>